services:
  - type: web
    name: bebesebes-api
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: MODEL_PATH
        value: uyku_bebek.h5
      - key: LABELS_PATH
        value: uyku_bebek_classes.npy
      - key: ALLOWED_ORIGINS
        value: https://bebesebes.netlify.app
